name: zamonia
version:        0.2.0.2
description:    Please see the README on GitHub at <https://github.com/Luc-Saccoccio/zamonia>
homepage:       https://github.com/Luc-Saccoccio/zamonia
bug-reports:    https://github.com/Luc-Saccoccio/zamonia/issues
author:         Luc Saccoccio
maintainer:     Luc-Saccoccio
copyright:      2021 Luc Saccoccio
license:        MIT
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md

library:
  source-dirs: src
  default-extensions: StrictData
  exposed-modules:
      - Zamonia
      - Zamonia.UI
  other-modules:
      - Paths_zamonia
      - Zamonia.Work
      - Zamonia.Film
      - Zamonia.Series
      - Zamonia.Book
  dependencies:
    - base >=4.7 && <5
    - aeson
    - aeson
    - aeson-pretty
    - bytestring
    - cassava
    - text-replace
    - typed-process
    - sqlite-simple
    - text
    - brick
    - vector
    - vty
    - microlens
    - microlens-th

executable:
  source-dirs: app
  main: Main.hs
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -threaded -O2 -rtsopts -with-rtsopts=-N
  dependencies:
    - base >=4.7 && <5
    - optparse-applicative
    - sqlite-simple
    - text
    - cassava
    - directory
    - zamonia

# tests:
#   source-dirs: test
#   main: Spec.hs
#   other-modules:
#       Paths_zamonia
#   ghc-options: -threaded -rtsopts -with-rtsopts=-N
#   dependencies:
#     - base >=4.7 && <5
#     - zamonia
